### ISSUE TITLE
本地运行正常，deploy后报This site has crashed

### ISSUE THREAD

**Issue by leetschau** [maodouio/meteor-master-classes#9]
本地运行`MONGO_URL="mongodb://localhost:27017/test" meteor`后运行正常，
deploy后报This site has crashed
查询日志：

```
$ meteor logs welog-lichao.meteor.com
[Thu Apr 16 2015 10:00:03 GMT+0000 (UTC)] INFO STATUS null -> starting
[Thu Apr 16 2015 10:00:03 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:00:03 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] WARNING                         throw(ex);
^
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] WARNING Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] INFO STATUS running -> starting
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:00:09 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:00:10 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Thu Apr 16 2015 10:00:10 GMT+0000 (UTC)] WARNING Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:00:10 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:00:10 GMT+0000 (UTC)] INFO STATUS running -> starting
[Thu Apr 16 2015 10:00:10 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:00:10 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:00:11 GMT+0000 (UTC)] WARNING 
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Thu Apr 16 2015 10:00:11 GMT+0000 (UTC)] WARNING Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:00:11 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:00:11 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Thu Apr 16 2015 10:00:17 GMT+0000 (UTC)] INFO HIT / 114.247.236.201
[Thu Apr 16 2015 10:00:23 GMT+0000 (UTC)] INFO HIT / 114.247.236.201
[Thu Apr 16 2015 10:00:23 GMT+0000 (UTC)] INFO HIT /favicon.ico 114.247.236.201
[Thu Apr 16 2015 10:00:24 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:00:24 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Thu Apr 16 2015 10:00:24 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:00:25 GMT+0000 (UTC)] WARNING 
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
[Thu Apr 16 2015 10:00:25 GMT+0000 (UTC)] WARNING                         throw(ex);
^
[Thu Apr 16 2015 10:00:25 GMT+0000 (UTC)] WARNING Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:00:25 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Thu Apr 16 2015 10:00:25 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:00:28 GMT+0000 (UTC)] INFO HIT /favicon.ico 114.247.236.201
[Thu Apr 16 2015 10:00:29 GMT+0000 (UTC)] INFO HIT /favicon.ico null
[Thu Apr 16 2015 10:00:34 GMT+0000 (UTC)] INFO HIT /favicon.ico 114.247.236.201
[Thu Apr 16 2015 10:00:49 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Thu Apr 16 2015 10:00:49 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:00:49 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:00:50 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
[Thu Apr 16 2015 10:00:50 GMT+0000 (UTC)] WARNING                         throw(ex);
^
[Thu Apr 16 2015 10:00:50 GMT+0000 (UTC)] WARNING Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:00:50 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Thu Apr 16 2015 10:00:50 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:01:27 GMT+0000 (UTC)] INFO HIT / 114.247.236.201
[Thu Apr 16 2015 10:01:33 GMT+0000 (UTC)] INFO HIT / 114.247.236.201
[Thu Apr 16 2015 10:01:38 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:01:38 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Thu Apr 16 2015 10:01:38 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:01:44 GMT+0000 (UTC)] WARNING /meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
[Thu Apr 16 2015 10:01:44 GMT+0000 (UTC)] WARNING Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:01:48 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:01:48 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Thu Apr 16 2015 10:03:23 GMT+0000 (UTC)] INFO HIT / 111.69.141.55
[Thu Apr 16 2015 10:03:29 GMT+0000 (UTC)] INFO HIT / 111.69.141.55
[Thu Apr 16 2015 10:03:30 GMT+0000 (UTC)] INFO HIT /favicon.ico 111.69.141.55
[Thu Apr 16 2015 10:03:36 GMT+0000 (UTC)] INFO HIT /favicon.ico 111.69.141.55
[Thu Apr 16 2015 10:04:25 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:04:25 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Thu Apr 16 2015 10:04:25 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:04:36 GMT+0000 (UTC)] WARNING 
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:04:36 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:04:36 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Thu Apr 16 2015 10:09:28 GMT+0000 (UTC)] NOTICE Starting application on port 11659
[Thu Apr 16 2015 10:09:28 GMT+0000 (UTC)] INFO STATUS waiting -> starting
[Thu Apr 16 2015 10:09:28 GMT+0000 (UTC)] INFO STATUS starting -> running
[Thu Apr 16 2015 10:09:34 GMT+0000 (UTC)] WARNING 
/meteor/dev_bundles/0.4.18/lib/node_modules/fibers/future.js:245
throw(ex);
^
Error: Author is required
at getErrorObject (packages/aldeed:collection2/collection2.js:369:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:352:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:154:1)
at app/server/seeds.js:4:11
at /meteor/containers/19e7b256-76e5-4bf6-8a27-a173f3cf4f78/bundle/programs/server/boot.js:229:5
[Thu Apr 16 2015 10:09:34 GMT+0000 (UTC)] ERROR Application crashed with code: 8
[Thu Apr 16 2015 10:09:34 GMT+0000 (UTC)] INFO STATUS running -> waiting
[Thu Apr 16 2015 10:09:46 GMT+0000 (UTC)] INFO HIT / 223.104.3.254
[Thu Apr 16 2015 10:09:52 GMT+0000 (UTC)] INFO HIT / 223.104.3.254
[Thu Apr 16 2015 10:09:58 GMT+0000 (UTC)] INFO HIT / 223.104.3.254
[Thu Apr 16 2015 10:10:04 GMT+0000 (UTC)] INFO HIT / 223.104.3.254
[Thu Apr 16 2015 10:10:30 GMT+0000 (UTC)] INFO HIT / 223.104.3.254
[Thu Apr 16 2015 10:10:36 GMT+0000 (UTC)] INFO HIT / 223.104.3.254
```

**Comment by kevingzhang** [comment]
需要看你的 mup.json 部署设置. 如果你部署时候要求本地27017 有 mongo, 那么那你就需要设置. 我建议全部使用缺省, 不要自己去定义 mongodb, 除非你使用第三方的 mongodb hosting service, 比如 compose.io

**Comment by limingth** [comment]
这个问题昨天晚上实验课已经解决，crash 的原因，
1. 是 seeds.js 中需要 server 启动添加5个默认的post，但是 Meteor.userId() 的调用当时没有用户登录，会出问题。
2. 是因为 meteor 是个老版本，好像 underscore 有些函数不能用，所以需要 meteor update 一下就好了。

## 

李明 / maodou.io

2015-04-17 6:03 GMT+08:00 kevingzhang notifications@github.com:
